# Generated by Django 5.0.4 on 2024-04-13 05:42

import ckeditor.fields
import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ma_dieu', models.CharField(max_length=10)),
                ('ten_dieu', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HocKy_NamHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoc_ky', models.IntegerField(choices=[(1, 'Một'), (2, 'Hai'), (3, 'Ba')])),
                ('nam_hoc', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ma_khoa', models.CharField(max_length=10)),
                ('ten_khoa', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('role', models.IntegerField(choices=[(1, 'Sinh Viên'), (2, 'Trợ lý sinh viên'), (3, 'Chuyên viên công tác sinh viên')], null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('tro_ly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=255)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.baiviet')),
                ('tai_khoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoatDongNgoaiKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ma_hoat_dong', models.CharField(max_length=10, unique=True)),
                ('ten_hoat_dong', models.TextField()),
                ('ngay', models.DateTimeField()),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('diem_ren_luyen', models.IntegerField(default=15)),
                ('dieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.dieu')),
                ('hk_nh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.hocky_namhoc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='baiviet',
            name='hoat_dong_ngoai_khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.hoatdongngoaikhoa'),
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ma_lop', models.CharField(max_length=10)),
                ('ten_lop', models.CharField(max_length=255)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.khoa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('mssv', models.CharField(max_length=10)),
                ('ho_ten', models.CharField(max_length=255)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.BooleanField()),
                ('dia_chi', models.TextField()),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.lop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiemRenLuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('diem_tong', models.IntegerField()),
                ('hk_nh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.hocky_namhoc')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.sinhvien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='baiviet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='baiviets', to='trainingpoint.tag'),
        ),
        migrations.CreateModel(
            name='ThamGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Điểm danh'), (2, 'Báo thiếu')], null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('hoat_dong_ngoai_khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.hoatdongngoaikhoa')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='MinhChung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('anh_minh_chung', cloudinary.models.CloudinaryField(max_length=255)),
                ('tham_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.thamgia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hoatdongngoaikhoa',
            name='sinh_vien',
            field=models.ManyToManyField(through='trainingpoint.ThamGia', to='trainingpoint.sinhvien'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.baiviet')),
                ('tai_khoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tai_khoan', 'bai_viet')},
            },
        ),
    ]
