# Generated by Django 5.0.4 on 2024-04-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieu',
            name='ma_dieu',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='khoa',
            name='ma_khoa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lop',
            name='ma_lop',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='mssv',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
