# Generated by Django 5.0.4 on 2024-04-18 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0002_alter_dieu_ma_dieu_alter_khoa_ma_khoa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.baiviet')),
                ('tai_khoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tai_khoan', 'bai_viet')},
            },
        ),
    ]
