# Generated by Django 5.0.4 on 2024-04-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='gioi_tinh',
            field=models.IntegerField(choices=[(1, 'Nam'), (2, 'Nữ')]),
        ),
    ]
