# Generated by Django 5.0.4 on 2024-04-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0005_alter_hoatdongngoaikhoa_diem_ren_luyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocky_namhoc',
            name='nam_hoc',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='hocky_namhoc',
            unique_together={('hoc_ky', 'nam_hoc')},
        ),
    ]
