# Generated by Django 5.0.4 on 2024-04-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0007_alter_thamgia_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thamgia',
            name='state',
            field=models.IntegerField(choices=[(0, 'Đăng ký'), (1, 'Điểm danh'), (2, 'Báo thiếu')], null=True),
        ),
    ]
