# Generated by Django 5.0.4 on 2024-04-28 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0008_alter_thamgia_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroLySinhVien_Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.khoa')),
                ('tro_ly_sinh_vien', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
