# Generated by Django 5.0.4 on 2024-04-29 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0006_alter_hocky_namhoc_nam_hoc'),
        ('trainingpoint', '0008_alter_thamgia_state'),
    ]

    operations = [
    ]
