# Generated by Django 5.0.4 on 2024-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0009_trolysinhvien_khoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='role',
            field=models.IntegerField(choices=[(1, 'Sinh Viên'), (2, 'Trợ lý sinh viên'), (3, 'Chuyên viên công tác sinh viên'), (4, 'Admin')], null=True),
        ),
    ]
