# Generated by Django 5.0.4 on 2024-04-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0009_merge_20240429_0924'),
        ('trainingpoint', '0010_alter_taikhoan_role'),
    ]

    operations = [
    ]
