# Generated by Django 5.0.4 on 2024-05-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0011_merge_20240429_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='cccd',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
