# Generated by Django 5.0.4 on 2024-05-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0012_sinhvien_cccd_sinhvien_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='cccd',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
