# Generated by Django 5.0.4 on 2024-05-16 08:30

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0013_alter_sinhvien_cccd_alter_sinhvien_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='tai_khoan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='tro_ly',
            field=models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='thamgia',
            name='state',
            field=models.IntegerField(choices=[(0, 'Đăng ký'), (1, 'Điểm danh'), (2, 'Báo thiếu')], default=0),
        ),
    ]
