# Generated by Django 5.0.4 on 2024-05-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0014_sinhvien_tai_khoan_alter_baiviet_tro_ly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='tai_khoan',
        ),
    ]
