# Generated by Django 5.0.4 on 2024-05-24 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0015_remove_sinhvien_tai_khoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieu',
            name='diem_toi_da',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='minhchung',
            name='tham_gia',
            field=models.ForeignKey(limit_choices_to={'state': 2}, on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.thamgia', unique=True),
        ),
    ]
