# Generated by Django 5.0.4 on 2024-05-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0016_dieu_diem_toi_da_alter_minhchung_tham_gia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minhchung',
            name='tham_gia',
            field=models.ForeignKey(limit_choices_to={'state': 2}, on_delete=django.db.models.deletion.CASCADE, to='trainingpoint.thamgia'),
        ),
    ]
