# Generated by Django 5.0.4 on 2024-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0017_alter_minhchung_tham_gia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='ho',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='ten',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
