# Generated by Django 5.0.4 on 2024-06-12 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0018_sinhvien_ho_sinhvien_ten'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baiviet',
            options={'verbose_name_plural': 'Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Bình luận'},
        ),
        migrations.AlterModelOptions(
            name='diemrenluyen',
            options={'verbose_name_plural': 'Điểm rèn luyện'},
        ),
        migrations.AlterModelOptions(
            name='dieu',
            options={'verbose_name_plural': 'Điều'},
        ),
        migrations.AlterModelOptions(
            name='hoatdongngoaikhoa',
            options={'verbose_name_plural': 'Hoạt động ngoại khóa'},
        ),
        migrations.AlterModelOptions(
            name='hocky_namhoc',
            options={'verbose_name_plural': 'Học kỳ - Năm học'},
        ),
        migrations.AlterModelOptions(
            name='khoa',
            options={'verbose_name_plural': 'Khoa'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name_plural': 'Like'},
        ),
        migrations.AlterModelOptions(
            name='lop',
            options={'verbose_name_plural': 'Lớp'},
        ),
        migrations.AlterModelOptions(
            name='minhchung',
            options={'verbose_name_plural': 'Minh chứng (Báo thiếu)'},
        ),
        migrations.AlterModelOptions(
            name='sinhvien',
            options={'verbose_name_plural': 'Sinh viên'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tag'},
        ),
        migrations.AlterModelOptions(
            name='taikhoan',
            options={'verbose_name_plural': 'Tài Khoản'},
        ),
        migrations.AlterModelOptions(
            name='thamgia',
            options={'verbose_name_plural': 'Tham gia'},
        ),
        migrations.AlterModelOptions(
            name='trolysinhvien_khoa',
            options={'verbose_name_plural': 'Trợ lý sinh viên - Khoa'},
        ),
        migrations.AlterUniqueTogether(
            name='hocky_namhoc',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='tro_ly',
            field=models.ForeignKey(limit_choices_to={'role__in': [2, 3]}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
